// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/popy-resume/Dossier.tsx": () => import("../components/mockups/popy-resume/Dossier.tsx"),
  "./components/mockups/popy-resume/SignalBoard.tsx": () => import("../components/mockups/popy-resume/SignalBoard.tsx")
};
